spring:
  datasource:
    url: jdbc:postgresql://java-postgres:5432/postgres #//Your DB
    username: postgres #//Your name
    password: relocate #//Your password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    locations: classpath:db/migration
    default-schema: flyway_schema
