version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: java-postgres
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=relocate'
    ports:
      - "5432:5432"

  backend:
    build: ./
    container_name: java-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
